### ISSUE TITLE
想问一下，私钥怎么获取呀

### ISSUE THREAD

**Issue by li-trong** [zhanlan123/YXlogDecode#15]

**Comment by zhanlan123** [comment]
![image](https://github.com/user-attachments/assets/cca313fc-6a5e-4908-975d-adc23ba9c525)
![image](https://github.com/user-attachments/assets/8d5cc078-9033-46a1-9f46-6748c97a4f7c)
![image](https://github.com/user-attachments/assets/bf08214a-aaa9-4847-b99e-6a1adfa2d869)
![image](https://github.com/user-attachments/assets/1266cb71-c9ef-4e00-97ee-8f9bd752c8cd)
