### ISSUE TITLE
启动白屏

### ISSUE THREAD

**Issue by zhuzhutai** [zhanlan123/YXlogDecode#16]
![image](https://github.com/user-attachments/assets/b60e1179-c84c-402f-9862-ff54ecd42e58)
不知道为什么下载自带jre的版本，运行起来是白屏。win11

**Comment by zhanlan123** [comment]
当前没有win11电脑。我研究一下。

**Comment by zhanlan123** [comment]
![1722580495691](https://github.com/user-attachments/assets/599b1eb5-ce17-452a-ad30-b73de23c3df4)
虚拟机中，没有问题。我更新一下库版本，你再试试。1.9.2版本。

**Comment by zhuzhutai** [comment]
> ![1722580495691](https://github.com/user-attachments/assets/599b1eb5-ce17-452a-ad30-b73de23c3df4)
> 虚拟机中，没有问题。我更新一下库版本，你再试试。1.9.2版本。

感谢大佬，有时间我再试试，兴许是我系统原因。我找时间换个电脑。
