### ISSUE TITLE
请问无加密解码是调用的哪个方法，可以直接在Android项目里使用吗

### ISSUE THREAD

**Issue by wuxiantaosu** [zhanlan123/YXlogDecode#3]

**Comment by zhanlan123** [comment]
忘记说明了。无加密，可以随便选择一个密钥。

**Comment by zhanlan123** [comment]
如果需要在安卓中使用，直接使用decode-core，然后根据test里面的调用方式。应该可以使用。我周末回去试试。当前有点忙。

**Comment by wuxiantaosu** [comment]
***@***.*** 


***@***.***
 
发件人： zhanlan123
发送时间： 2023-04-20 17:44
收件人： zhanlan123/YXlogDecode
抄送： wuxiantaosu; Author
主题： Re: [zhanlan123/YXlogDecode] 请问无加密解码是调用的哪个方法，可以直接在Android项目里使用吗 (Issue #3)
如果需要在安卓中使用，直接使用decode-core，然后根据test里面的调用方式。应该可以使用。我周末回去试试。当前有点忙。

**Comment by zhanlan123** [comment]
android里面不能使用，需要更改解密库。等我有时间改改。

**Comment by zhanlan123** [comment]
最新提交已经支持
