### ISSUE TITLE
1.6 版本自带 jre 解密出现异常NoSuchProviderException

### ISSUE THREAD

**Issue by DituLin** [zhanlan123/YXlogDecode#5]
版本：decode-ui-1.6-with-jre-win.zip
Windows 版本：win 11

步骤：使用密钥解密
异常信息：java.security.NoSuchProviderException: JCE cannot authenticate the provider BC

<img width="773" alt="image" src="https://github.com/zhanlan123/YXlogDecode/assets/13131323/231e2588-07c6-4569-bcb5-9864f99d1bce">

**Comment by DituLin** [comment]
已解决
由于电脑本身已有安装Android Studio 带有 OpenJDK ，将 AS 安装目录下 jre 目录拷贝替换了 decode-ui-1.6-with-jre-win 自带 jre目录。

**Comment by jiaoyaning** [comment]
666
